CREATE SCHEMA aop;

CREATE TABLE aop.mv_toxcast_aop_map (
	toxcast_aeid int4 NULL,
	entrez_gene_id int4 NULL,
	event_number int4 NULL,
	event_link varchar NULL,
	aop_number int4 NULL,
	aop_link varchar NULL,
	id serial4 NOT NULL
);

CREATE SCHEMA invitro;

CREATE TABLE invitro.mv_assay_agg (
	aeid int8 NULL,
	active_mc numeric(23) NULL,
	total_mc int8 NULL,
	active_sc numeric(23) NULL,
	total_sc int8 NULL,
	export_date date NULL,
	data_version varchar(28) NULL
);

CREATE TABLE invitro.mv_assay_annotation (
	aeid int8 NULL,
	assay_component_endpoint_name varchar(255) NULL,
	assay_component_endpoint_desc text NULL,
	assay_function_type varchar(255) NULL,
	normalized_data_type varchar(255) NULL,
	burst_assay int2 NULL,
	key_positive_control varchar(255) NULL,
	signal_direction varchar(255) NULL,
	intended_target_type varchar(255) NULL,
	intended_target_type_sub varchar(255) NULL,
	intended_target_family varchar(255) NULL,
	intended_target_family_sub varchar(255) NULL,
	cell_viability_assay int2 NULL,
	acid int4 NULL,
	assay_component_name varchar(255) NULL,
	assay_component_desc text NULL,
	assay_component_target_desc text NULL,
	parameter_readout_type varchar(255) NULL,
	assay_design_type varchar(255) NULL,
	assay_design_type_sub varchar(255) NULL,
	biological_process_target varchar(255) NULL,
	detection_technology_type varchar(255) NULL,
	detection_technology_type_sub varchar(255) NULL,
	detection_technology varchar(255) NULL,
	key_assay_reagent_type varchar(255) NULL,
	key_assay_reagent varchar(255) NULL,
	technological_target_type varchar(255) NULL,
	technological_target_type_sub varchar(255) NULL,
	aid int4 NULL,
	assay_name varchar(255) NULL,
	assay_desc text NULL,
	timepoint_hr float8 NULL,
	organism_id int4 NULL,
	organism varchar(255) NULL,
	ncbi_taxon_id int4 NULL,
	taxon_name varchar(255) NULL,
	common_name varchar(255) NULL,
	lineage varchar(255) NULL,
	tissue varchar(255) NULL,
	cell_format varchar(255) NULL,
	cell_free_component_source varchar(255) NULL,
	cell_short_name varchar(255) NULL,
	cell_growth_mode varchar(255) NULL,
	assay_footprint varchar(255) NULL,
	assay_format_type varchar(255) NULL,
	assay_format_type_sub varchar(255) NULL,
	content_readout_type varchar(255) NULL,
	dilution_solvent varchar(255) NULL,
	dilution_solvent_percent_max float8 NULL,
	asid int4 NULL,
	assay_source_name varchar(255) NULL,
	assay_source_long_name varchar(255) NULL,
	assay_source_desc varchar(255) NULL,
	clowder_uid varchar(45) NULL,
	gene json NULL,
	assay_list json NULL,
	citations json NULL,
	assay_reagent json NULL,
	mc2_methods json NULL,
	mc3_methods json NULL,
	mc4_methods json NULL,
	mc5_methods json NULL,
	mc6_methods json NULL,
	sc1_methods json NULL,
	sc2_methods json NULL,
	export_date date NULL,
	data_version varchar(28) NULL
);

CREATE TABLE invitro.mv_bioactivity (
	m4id int8 NULL,
	aeid int8 NULL,
	spid varchar(50) NULL,
	chid int4 NULL,
	casn varchar(45) NULL,
	chnm varchar(255) NULL,
	dsstox_substance_id varchar(255) NULL,
	bmad float8 NULL,
	resp_max float8 NULL,
	resp_min float8 NULL,
	max_mean float8 NULL,
	max_mean_conc float8 NULL,
	min_mean float8 NULL,
	min_mean_conc float8 NULL,
	max_med float8 NULL,
	max_med_conc float8 NULL,
	min_med float8 NULL,
	min_med_conc float8 NULL,
	max_med_diff float8 NULL,
	max_med_diff_conc float8 NULL,
	conc_max float8 NULL,
	conc_min float8 NULL,
	nconc int4 NULL,
	npts int4 NULL,
	nrep float8 NULL,
	nmed_gtbl_pos int4 NULL,
	nmed_gtbl_neg int4 NULL,
	m5id int8 NULL,
	modl varchar(5) NULL,
	hitc float8 NULL,
	fitc int2 NULL,
	coff float8 NULL,
	actp float8 NULL,
	model_type int2 NULL,
	chid_rep int2 NULL,
	stkc float8 NULL,
	stkc_unit varchar(50) NULL,
	tested_conc_unit varchar(50) NULL,
	mc3_param json NULL,
	mc4_param json NULL,
	mc5_param json NULL,
	mc6_param json NULL,
	mc7_param json NULL,
	export_date date NULL,
	data_version varchar(28) NULL
);

CREATE TABLE invitro.mv_bioactivity_model (
	id int4 NULL,
	dtxsid varchar(50) NULL,
	model varchar(255) NULL,
	receptor varchar(255) NULL,
	agonist varchar(255) NULL,
	antagonist varchar(255) NULL,
	binding varchar(255) NULL,
	help varchar(1024) NULL
);

CREATE TABLE invitro.mv_bioactivity_sc (
	s2id int8 NULL,
	aeid int4 NULL,
	spid varchar(50) NULL,
	chid int4 NULL,
	casn varchar(45) NULL,
	chnm varchar(255) NULL,
	dsstox_substance_id varchar(255) NULL,
	bmad float8 NULL,
	max_med float8 NULL,
	coff float8 NULL,
	hitc float8 NULL,
	chid_rep int2 NULL,
	stkc float8 NULL,
	stkc_unit varchar(50) NULL,
	tested_conc_unit varchar(50) NULL,
	sc1_param json NULL,
	export_date date NULL,
	data_version varchar(28) NULL
);

CREATE TABLE invitro.mv_chemical_agg (
	dsstox_substance_id varchar(255) NULL,
	active_mc numeric(23) NULL,
	total_mc int8 NULL,
	active_sc numeric(23) NULL,
	total_sc int8 NULL,
	cytotox_median_raw float8 NULL,
	cytotox_mad float8 NULL,
	global_mad float8 NULL,
	cytotox_median_log float8 NULL,
	cytotox_median_um float8 NULL,
	cytotox_lower_bound_um float8 NULL,
	cytotox_lower_bound_log float8 NULL,
	ntested float8 NULL,
	nhit float8 NULL,
	export_date date NULL,
	data_version text NULL
);

CREATE TABLE invitro.mv_chemical_analytical_qc (
	analytical_qc_id int8 NULL,
	dsstox_substance_id varchar(255) NULL,
	chnm varchar(255) NULL,
	spid varchar(50) NULL,
	qc_level varchar(50) NULL,
	p_or_caution varchar(50) NULL,
	t0 varchar(50) NULL,
	t4 varchar(50) NULL,
	"call" varchar(50) NULL,
	annotation varchar(2048) NULL,
	flags varchar(255) NULL,
	average_mass varchar(50) NULL,
	log10_vapor_pressure_opera_pred varchar(50) NULL,
	logkow_octanol_water_opera_pred varchar(50) NULL,
	export_date date NULL,
	data_version text NULL
);

CREATE TABLE invitro.search_assay (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	aeid int8 NULL,
	search_name varchar(50) NULL,
	search_value varchar(200) NULL,
	search_value_desc text NULL,
	modified_value text NULL,
	data_version varchar(50) NULL,
	export_date date NULL
);

CREATE SCHEMA ch;

CREATE TABLE ch.v_chemical_details (
	id int8,
	dtxsid varchar(255),
	dtxcid varchar(255),
	casrn varchar(255),
	compound_id int4,
	generic_substance_id int4,
	preferred_name text,
	active_assays int4,
	cpdata_count int8,
	mol_formula varchar(255),
	monoisotopic_mass numeric(20,10),
	percent_assays numeric,
	pubchem_count int4,
	pubmed_count float8,
	sources_count int8,
	qc_level int4,
	qc_level_desc varchar(255),
	stereo text,
	isotope int4,
	multicomponent int4,
	total_assays int8,
	toxcast_select text,
	pubchem_cid int4,
	mol_file text,
	mrv_file text,
	related_substance_count int8,
	related_structure_count int8,
	mol_image bytea,
	has_structure_image int4,
	iupac_name varchar(5000),
	smiles text,
	inchi_string text,
	average_mass numeric(10,5),
	inchikey varchar(255),
	qc_notes varchar(1024),
	qsar_ready_smiles text,
	ms_ready_smiles text,
	iris_link varchar(255),
	pprtv_link varchar(255),
	wikipedia_article varchar(255),
	expocat_median_prediction text,
	expocat text,
	nhanes text,
	toxval_data text,
	water_solubility_test float8,
	water_solubility_opera float8,
	viscosity_cp_cp_test_pred float8,
	vapor_pressure_mmhg_test_pred float8,
	vapor_pressure_mmhg_opera_pred float8,
	thermal_conductivity float8,
	tetrahymena_pyriformis float8,
	surface_tension float8,
	soil_adsorption_coefficient float8,
	oral_rat_ld50_mol float8,
	opera_km_days_opera_pred float8,
	octanol_water_partition float8,
	octanol_air_partition_coeff float8,
	melting_point_degc_test_pred float8,
	melting_point_degc_opera_pred float8,
	hr_fathead_minnow float8,
	hr_diphnia_lc50 float8,
	henrys_law_atm float8,
	flash_point_degc_test_pred float8,
	devtox_test_pred float8,
	density float8,
	boiling_point_degc_test_pred float8,
	boiling_point_degc_opera_pred float8,
	biodegradation_half_life_days float8,
	bioconcentration_factor_test_pred float8,
	bioconcentration_factor_opera_pred float8,
	atmospheric_hydroxylation_rate float8,
	ames_mutagenicity_test_pred float8,
	pkaa_opera_pred float8,
	pkab_opera_pred float8,
	descriptor_string_tsv varchar(20000),
	logd5_5 float8,
	logd7_4 float8,
	ready_bio_deg float8,
	mol_wgt numeric(10,5),
	is_markush bool
);
