name: email 

on:
  schedule:
    - cron: '00 9 * * 1,4'
    
env:
    REPORT_DIR: /data/watchtower/ctx-API/container-results/api-bioactivity

jobs:
    send-email:
        runs-on: "th878"
        steps:
        - name: Email latest report
          uses: USEPA/email-report@main
          with:
                report_path: ${{ env.REPORT_DIR }}/bioactivity-report.html
                recipients: ${{ vars.REPORT_RECIPIENTS }}
                sender: ${{ vars.REPORT_SENDER }}
                subject: "CTX-bioactivity-API container scanning results"
                body: |
                    Hello,

                    Please find attached the CTX-bioactivity-API container scan report.

                    Best regards.
